name: insulinoterapia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.3
  firebase_core: ^2.30.0
  firebase_remote_config: ^4.3.14
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_insulin.svg
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
