// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFQI3etH8zRityN1RQT-Q5aJxt2gsVCg',
    appId: '1:438732852041:android:433169a05c146a29a92898',
    messagingSenderId: '438732852041',
    projectId: 'app-insulina',
    databaseURL: 'https://app-insulina-default-rtdb.firebaseio.com',
    storageBucket: 'app-insulina.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZviZ2ee275UOJfuoisTAfz5jzmUt5Ug',
    appId: '1:438732852041:web:6c44bf14bb079326a92898',
    messagingSenderId: '438732852041',
    projectId: 'app-insulina',
    authDomain: 'app-insulina.firebaseapp.com',
    databaseURL: 'https://app-insulina-default-rtdb.firebaseio.com',
    storageBucket: 'app-insulina.firebasestorage.app',
    measurementId: 'G-8FP1ZLH93Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMJbd6JpHkZDOhjbFZB1LNNgnslmFifa8',
    appId: '1:438732852041:ios:d2893db8994b57a9a92898',
    messagingSenderId: '438732852041',
    projectId: 'app-insulina',
    databaseURL: 'https://app-insulina-default-rtdb.firebaseio.com',
    storageBucket: 'app-insulina.firebasestorage.app',
    iosBundleId: 'com.healium.insulinoterapia',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJbd6JpHkZDOhjbFZB1LNNgnslmFifa8',
    appId: '1:438732852041:ios:d2893db8994b57a9a92898',
    messagingSenderId: '438732852041',
    projectId: 'app-insulina',
    databaseURL: 'https://app-insulina-default-rtdb.firebaseio.com',
    storageBucket: 'app-insulina.firebasestorage.app',
    iosBundleId: 'com.healium.insulinoterapia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTZviZ2ee275UOJfuoisTAfz5jzmUt5Ug',
    appId: '1:438732852041:web:e0def002a7d8e011a92898',
    messagingSenderId: '438732852041',
    projectId: 'app-insulina',
    authDomain: 'app-insulina.firebaseapp.com',
    databaseURL: 'https://app-insulina-default-rtdb.firebaseio.com',
    storageBucket: 'app-insulina.firebasestorage.app',
    measurementId: 'G-8SC7SHZMMF',
  );

}